[package]
name = "x86-exts"
version = "0.1.0"
authors = ["Luuk van der Duim <luukvanderduim@gmail.com>"]
edition = "2018"

[profile.release]
opt-level = 3
lto = true
debug = 0
strip = true

[dependencies]
argh = "0.1.8"
elf_rs = "0.2.0"
iced-x86 = "1.17.0"

